apiVersion: 1
datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus       # VM은 Prometheus 호환 쿼리 API 제공
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
